version: "3"
agent:
  authtoken: ""
tunnels:
  ssh:
    proto: tcp
    addr: 22
    hostname: ""
  http:
    proto: http
    addr: 80
    hostname: ""
  http-8081:
    proto: http
    addr: 8081
    hostname: ""